version: '3'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
  web:
    build: .
    command: bundle exec rails s -p 8080 -b '0.0.0.0'
    env_file:
      - .env
    tty: true
    stdin_open: true
    volumes:
      - .:/gh_userinfo
    ports:
      - "8080:8080"
    depends_on:
      - db
